### ISSUE TITLE
Settling to only add torrent from scraper 

### ISSUE THREAD

**Issue by kagz-93** [AyushSehrawat/rdm#78]
Is this a enhancement to already existing feature ?
- No 

Currently RDM adds content to both the torrent and download section when using the scraper to add movies or TV series, id like for the files just to be added to the torrents section but not the downloads section if possible. Not to give a long explanation but I'm using real debrid with plex and when using RDM to add files they are not being recognized in my plex server because they are also added to the downloads section. If a setting could be added that just allows torrents to be added that would be really helpful. 

Thanks! 

**This feature is related to?**
Real Debrid

**Comment by AyushSehrawat** [comment]
Hello @IG2022 , i don't manage adding the link to rd, i send a HEAD request to the download url by torrentio and it adds it.

I can change this to just add hash to realdebrid torrents and not downloads but can take some time.

**Comment by AyushSehrawat** [comment]
Hm need to edit https://github.com/AyushSehrawat/rdm/blob/c14542609b23dece2a2ddc49476a37fef2f4c5aa/src/routes/app/scraper/%5Btype%5D/%5Bid%5D/%2Bpage.svelte#L92 function,

i can add a new button i guess

**Comment by kagz-93** [comment]
> Hello @IG2022 , i don't manage adding the link to rd, i send a HEAD request to the download url by torrentio and it adds it.
> 
> I can change this to just add hash to realdebrid torrents and not downloads but can take some time.

Hi @AyushSehrawat thanks for getting back to me so quickly! 

I would appreciate it if you could make that change when you have some time,  I really dont mind waiting. I just discovered this project and I'm really enjoying using the application it's just him this one thing that is affecting me.

**Comment by AyushSehrawat** [comment]
@IG2022 i need to add few more endpoints to get the add only torrent to rd working, since i need to select files and use instant availability endpoint to get the cached files. 
I am thinking to put some more effort into rewriting rdm, which i have already started. 

This will be fixed in it

**Comment by kagz-93** [comment]
> @IG2022 i need to add few more endpoints to get the add only torrent to rd working, since i need to select files and use instant availability endpoint to get the cached files. I am thinking to put some more effort into rewriting rdm, which i have already started.
> 
> This will be fixed in it

Thanks for considering this for the next update I really appreciate it and I am looking forward to it.
